### ISSUE TITLE
why  the new version is slower

### ISSUE THREAD

**Issue by xiaosefengyun** [OpenGene/fastp#363] opened 2021-09-23 07:44 UTC
fastp v0.20.0, time used: 358 seconds 
fastp v0.22.0, time used: 481 seconds 

The fastq file is the same
Worker compute is the same

Moreover, solid state drives and mechanical drives have no advantage in running speed.

**Comment by xiaosefengyun** [comment] 2021-09-23 07:45
fastp -i ERR1711796_1.fastq.gz -o filter_1.fast1.gz -I ERR1711796_2.fastq.gz -O filter_2.fast1.gz -Q --thread=16 --length_required=50 --n_base_limit=2 --compression=6
this is my cmd

**Comment by xiaosefengyun** [comment] 2021-09-23 07:52
I find the memory use is low about 3-4GB,  Is it possible that the memory is not fully used？ I guess

**Comment by sfchen** [comment] 2021-09-23 08:38
This may be caused by the new `duplication evaluation` feature, which  is more accurate than previous versions. You can try to add `--dont_eval_duplication` option to disable duplication rate evaluation, and the speed will be back.

In v0.23.0, the speed will be improved and be much faster than v0.20.0. v0.23.0 has not been released, but you can try it by downloading: http://opengene.org/fastp/fastp.0.23.0

**Comment by xiaosefengyun** [comment] 2021-09-23 08:40
very thanks, I will test v0.23.0 now

**Comment by xiaosefengyun** [comment] 2021-09-23 08:53
> This may be caused by the new `duplication evaluation` feature, which is more accurate than previous versions. You can try to add `--dont_eval_duplication` option to disable duplication rate evaluation, and the speed will be back.
> 
> In v0.23.0, the speed will be improved and be much faster than v0.20.0. v0.23.0 has not been released, but you can try it by downloading: http://opengene.org/fastp/fastp.0.23.0

fastp v0.23.0, time used: 496 seconds
v0.23.0 memory use increase to 20GB， but run time not reduce.

**Comment by xiaosefengyun** [comment] 2021-09-23 08:54
I test `--dont_eval_duplication` now

**Comment by sfchen** [comment] 2021-09-23 09:01
Can you try 4 threads, 6 threads and 8 threads? And then give me the result.

**Comment by xiaosefengyun** [comment] 2021-09-23 09:02
OK

**Comment by xiaosefengyun** [comment] 2021-09-23 09:11
> Can you try 4 threads, 6 threads and 8 threads? And then give me the result.

![image](https://user-images.githubusercontent.com/12832248/134481804-01ec3668-bfd5-4125-9f78-160b8fa0a1d3.png)

**Comment by xiaosefengyun** [comment] 2021-09-23 09:11
i use 4 threads but speed same

**Comment by sfchen** [comment] 2021-09-23 09:24
Okay, v0.23.0 has not been released. It will be released in about one week. The performance issue will be addressed when it's released.

Currently you can use old versions, for example v0.20.1, by downloading: http://opengene.org/fastp/fastp.0.20.1

**Comment by xiaosefengyun** [comment] 2021-09-23 09:25
OK thanks

**Comment by sfchen** [comment] 2021-09-25 03:56
Hi, I updated v0.23.0, and I believe it's faster than before, can you try again with: http://opengene.org/fastp/fastp.0.23.0

**Comment by xiaosefengyun** [comment] 2021-09-25 04:07
fastp -i ERR1711796_1.fastq.gz -o filter_1.fastq.gz -I ERR1711796_2.fastq.gz -O filter_2.fastq.gz -Q --thread=16 --length_required=50 --n_base_limit=2 --compression=6
fastp v0.23.0, time used: 112 seconds

It resloved

thank you  chen

**Closed** 2021-09-25 04:07 UTC
