### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by florathecat** [OpenGene/fastp#27] opened 2018-02-07 21:47 UTC
Hi,

I have a personal laptop and a work laptop. The personal one is a windows 10 hosting Ubuntu 16.04 on a Oracle virtual box (with anaconda and both python 2.7 and 3.6 installed) and the work laptop is a windows 7 hosting Ubuntu 16.04 on a VMware workstation (with anaconda and python 3.6 installed). I had no problem installing either AfterQC or fastp on my personal laptop.

However, when I was trying to install fastp (thinking that I don't want to install python 2.7 for AfterQC) on my work laptop through bioconda, it tells me that I have conflicts with other packages, as follows:

"Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - blaze -> pytables[version='>=3.0.0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - fastp
Use "conda info <package>" to see the dependencies for each package."

When I was trying to install directly from cloning from github, it also failed, with the following error message:

" /usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'fastp' failed
make: *** [fastp] Error 1 "

I realize that there must be some insufficiency within my work laptop but I don't know what it is, as I am pretty new to Linux system. I would really like to have it fixed because fastp is a really nicely made package for cleaning up and QC WGS reads. If you have any suggestions or useful tips for resolving this issue, please help me out.

Really appreciate your help. Thanks in advance.

Yun

**Comment by sfchen** [comment] 2018-02-09 07:32
Hi Yun,

Have you ever tried the prebuilt binary? It can be downloaded from: http://opengene.org/fastp/fastp

See more detail on the README page: https://github.com/OpenGene/fastp#get-fastp

**Comment by sfchen** [comment] 2018-02-09 07:33
BTW, the failure was caused by that your system was lack of `zlib`.

**Comment by florathecat** [comment] 2018-02-09 19:58
Many Thanks Shifu,

I have zlib 1.2.11 installed on my environment. However, fastp requires zlib 1.2.8. That's probably the reason to my downfall. I'll work on installing two versions of zlib to see if I can resolve the issue.

Yun

**Comment by sfchen** [comment] 2018-02-21 13:33
Yi Yun,

Any update? Can I close this issue now?

**Comment by florathecat** [comment] 2018-02-21 17:44
Hi Shifu,

Thanks for checking in. Yes you may close the ticket. I updated everything I could think of, including zlib, and miraculously got fastp installed last week. (Not sure what I did right though.) 

Thank you again so very much for your help.

Yun

**Comment by sfchen** [comment] 2018-02-24 03:09
Closing...

**Closed by sfchen** 2018-02-24 03:09 UTC
