### ISSUE TITLE
Option to merge overlapping PE reads?

### ISSUE THREAD

**Issue by peterjc** [OpenGene/fastp#139] opened 2019-03-08 16:03 UTC
From the main README file, you already have code to look for PE overlaps and use this for correcting mismatches & detecting adapters. Could you add an option to output only the merged reads?

Right now I would only want the overlaps as output (not interested in the non-overlapping reads).

This could replace the need to call a separate FASTQ pair-merging tool like ``pear`` or ``flash``,
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3933873/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3198573/

**Comment by sfchen** [comment] 2019-03-09 00:04
I promise to implement this in 3 days

**Comment by peterjc** [comment] 2019-03-09 09:50
Wow - there's not need to rush, but if you think this functionality is a good fit to FASTP, that'd be great. Thank you.

**Comment by sfchen** [comment] 2019-03-16 10:39
Hi guys, this function is implemented, please have a try and help to update this thread with the results.

# merge paired-end reads
For paired-end (PE) input, fastp supports stiching them by specifying the `-m/--merge` option. In this `merging` mode, the output will be a single file.

In the output file, a tag will `merged_xxx_yyy` be added to the read name to indicate that how many base pairs are from read1 and from read2, respectively. For example, `
@NB551106:9:H5Y5GBGX2:1:22306:18653:13119 1:N:0:GATCAG merged_150_15` 
means that 150bp are from read1, and 15bp are from read2. `fastp` prefers the bases in read1 since they usually have higher quality than read2.

For the pairs of reads that cannot be merged successfully, they will be both included in the output by default. But you can specify the `--chastity` option to discard the unmerged reads.

Same as the base correction feature, this function is also based on overlapping detection, which has adjustable parameters `overlap_len_require (default 30)` and `overlap_diff_limit (default 5)`.

**Comment by sfchen** [comment] 2019-03-16 10:40
Closing this issue since it's a dupe of https://github.com/OpenGene/fastp/issues/31

**Closed by sfchen** 2019-03-16 10:40 UTC

**Comment by peterjc** [comment] 2019-03-16 11:21
Lovely- I missed the old issue as I searched with different keywords - thank you 🙏
